const ITEM_NAME_CHANGED = 'ITEM_NAME_CHANGED'
const ITEM_EXPIRATION_DATE_CHANGED = 'ITEM_EXPIRATION_DATE_CHANGED'
const ITEM_QUANTITY_CHANGED = 'ITEM_QUANTITY_CHANGED'
const ITEM_IN_EDIT_MODE = 'ITEM_IN_EDIT_MODE'
const ITEM_DIALOG_INACTIVE = 'ITEM_DIALOG_INACTIVE'
const ITEM_DIALOG_EDIT = 'ITEM_DIALOG_EDIT'
const ITEM_DIALOG_ADD = 'ITEM_DIALOG_ADD'
const ITEM_DIALOG_OK = 'ITEM_DIALOG_OK'

export default {
    ITEM_NAME_CHANGED,
    ITEM_EXPIRATION_DATE_CHANGED,
    ITEM_QUANTITY_CHANGED,
    ITEM_IN_EDIT_MODE,
    ITEM_DIALOG_INACTIVE,
    ITEM_DIALOG_EDIT,
    ITEM_DIALOG_ADD,
    ITEM_DIALOG_OK
}